# Generated by Django 5.0.1 on 2026-04-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo_url',
            field=models.TextField(blank=True, help_text='Base64 encoded profile photo or URL', null=True),
        ),
    ]
