# Generated by Django 5.0.1 on 2026-04-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_password_alter_user_profile_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_code_id',
            field=models.CharField(blank=True, help_text='Unique QR code ID for attendance', max_length=50, null=True, unique=True),
        ),
    ]
