# Generated by Django 5.0.1 on 2026-05-19 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_qr_code_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Office latitude coordinate')),
                ('longitude', models.FloatField(help_text='Office longitude coordinate')),
                ('radius_meters', models.IntegerField(default=100, help_text='Allowed radius in meters')),
                ('address', models.CharField(blank=True, help_text='Office address description', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_by', models.ForeignKey(blank=True, help_text='HR/Manager who set this location', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Office Location',
                'verbose_name_plural': 'Office Location',
                'db_table': 'office_location',
            },
        ),
    ]
